# R6 corrective layer: generated R5 host -> Adaptive Arc Steering host.
# This is deliberately layered after the validated R5 generator so Alpha 6, disk
# control and the existing PS1 input plumbing remain untouched.
if(NOT DEFINED OMNICORE_ARC_HOST_INPUT OR NOT DEFINED OMNICORE_ARC_HOST_OUTPUT)
    message(FATAL_ERROR "PS1 adaptive-arc patch requires input/output paths")
endif()

file(READ "${OMNICORE_ARC_HOST_INPUT}" SOURCE)

function(arc_replace_required OLD NEW LABEL)
    string(FIND "${SOURCE}" "${OLD}" FOUND_AT)
    if(FOUND_AT EQUAL -1)
        message(FATAL_ERROR "PS1 adaptive-arc patch anchor missing: ${LABEL}")
    endif()
    string(REPLACE "${OLD}" "${NEW}" SOURCE "${SOURCE}")
    set(SOURCE "${SOURCE}" PARENT_SCOPE)
endfunction()

# Extend only the emulation-thread steering state. The existing accumulator becomes
# a fractional turn budget; no new Android timer/thread is introduced.
set(OLD [=[
        modernMovementActive_ = false;
        modernTurnSign_ = 0;
        modernTurnAccumulator_ = 0.0f;
        modernTankButtons_.store(0u, std::memory_order_release);
]=])
set(NEW [=[
        modernMovementActive_ = false;
        modernSteeringLatched_ = false;
        modernTurnSign_ = 0;
        modernMoveSign_ = 0;
        modernTurnAccumulator_ = 0.0f;
        modernTurnBurstRemaining_ = 0;
        modernTankButtons_.store(0u, std::memory_order_release);
]=])
arc_replace_required("${OLD}" "${NEW}" "adaptive arc reset state")

set(OLD [=[
    bool modernMovementActive_ = false;
    int modernTurnSign_ = 0;
    float modernTurnAccumulator_ = 0.0f;
    std::atomic<int> leftX_{0};
]=])
set(NEW [=[
    bool modernMovementActive_ = false;
    bool modernSteeringLatched_ = false;
    int modernTurnSign_ = 0;
    int modernMoveSign_ = 0;
    float modernTurnAccumulator_ = 0.0f;
    int modernTurnBurstRemaining_ = 0;
    std::atomic<int> leftX_{0};
]=])
arc_replace_required("${OLD}" "${NEW}" "adaptive arc state fields")

# Replace only the moving-turn resolver. Straight motion and turn-in-place above this
# anchor remain exactly as generated by R5.
set(OLD [=[
        const unsigned moveId = moveSign < 0 ? 4u : 5u;
        std::uint32_t mask = modernButtonBit(moveId);

        // Keep a small straight cone so normal thumb drift stays straight, but make it
        // narrower than R4 so an intentional diagonal begins curving sooner.
        constexpr float kStraightSteerDeadzone = 0.12f;
        constexpr float kStraightConeRatio = 0.18f;
        if (turnSign == 0 || ax <= kStraightSteerDeadzone || ax < ay * kStraightConeRatio) {
            modernTurnSign_ = 0;
            modernTurnAccumulator_ = 0.0f;
            modernTankButtons_.store(mask, std::memory_order_release);
            return;
        }

        // A direction change gets an immediate correction frame. Later correction
        // frames are sigma-delta distributed according to analog intent, one decision
        // per retro_run, so PAL/NTSC and Android timer jitter cannot change the pattern.
        if (turnSign != modernTurnSign_) {
            modernTurnSign_ = turnSign;
            modernTurnAccumulator_ = 1.0f;
        }

        const float normalized = std::clamp(
            (ax - kStraightSteerDeadzone) / (1.0f - kStraightSteerDeadzone), 0.0f, 1.0f);

        // R5 response curve: more linear through the middle than R4. This preserves
        // micro-corrections near centre while making a 30-60 degree stick angle produce
        // a visibly useful course change instead of an almost-straight path.
        const float curved = 0.62f * normalized + 0.38f * normalized * normalized;
        constexpr float kMinTurnDuty = 0.16f;
        constexpr float kMaxTurnDuty = 0.98f;
        float duty = kMinTurnDuty + (kMaxTurnDuty - kMinTurnDuty) * curved;

        // Gated diagonal boost. Tiny sideways drift does not get boosted; once both
        // axes are deliberately engaged, the boost rises smoothly toward a true
        // diagonal. This increases curve authority without returning to held UP+RIGHT.
        const float minAxis = std::min(ax, ay);
        const float maxAxis = std::max(ax, ay);
        const float diagonalRatio = maxAxis > 0.0001f ? std::clamp(minAxis / maxAxis, 0.0f, 1.0f) : 0.0f;
        const float diagonalGate = std::clamp((minAxis - 0.20f) / 0.42f, 0.0f, 1.0f);
        duty += 0.16f * diagonalRatio * diagonalGate;

        // Near the outer rim the player's intent is strong, so allow a little extra
        // authority before the dedicated turn-in-place sector takes over.
        const float edgeBoost = std::clamp((ax - 0.72f) / 0.28f, 0.0f, 1.0f);
        duty += 0.06f * edgeBoost;
        duty = std::clamp(duty, kMinTurnDuty, kMaxTurnDuty);

        modernTurnAccumulator_ += duty;
        const bool turnThisFrame = modernTurnAccumulator_ >= 1.0f;
        if (turnThisFrame) modernTurnAccumulator_ -= 1.0f;

        if (turnThisFrame) mask |= modernButtonBit(turnSign < 0 ? 6u : 7u);
        modernTankButtons_.store(mask, std::memory_order_release);
]=])
set(NEW [=[
        const unsigned moveId = moveSign < 0 ? 4u : 5u;
        std::uint32_t mask = modernButtonBit(moveId);

        // Steering is derived from STICK ANGLE instead of raw X magnitude. At a real
        // 45-degree diagonal ax/(ax+ay) is ~0.5 regardless of radial distance, so the
        // diagonal cannot vanish merely because touch normalization changed magnitude.
        const float axisSum = ax + ay;
        const float steerRatio = axisSum > 0.0001f ? ax / axisSum : 0.0f;
        constexpr float kSteerEnterRatio = 0.135f;
        constexpr float kSteerExitRatio = 0.090f;
        constexpr float kSteerEnterAxis = 0.115f;
        constexpr float kSteerExitAxis = 0.080f;

        if (!modernSteeringLatched_) {
            modernSteeringLatched_ = turnSign != 0 && ax >= kSteerEnterAxis && steerRatio >= kSteerEnterRatio;
        } else if (turnSign == 0 || ax < kSteerExitAxis || steerRatio < kSteerExitRatio) {
            modernSteeringLatched_ = false;
        }

        if (!modernSteeringLatched_) {
            modernTurnSign_ = 0;
            modernMoveSign_ = moveSign;
            modernTurnAccumulator_ = 0.0f;
            modernTurnBurstRemaining_ = 0;
            modernTankButtons_.store(mask, std::memory_order_release);
            return;
        }

        // The analog stick describes desired travel direction. When backing up, invert
        // the digital turn so down-right actually bends the backward path to the right.
        const int effectiveTurnSign = moveSign > 0 ? -turnSign : turnSign;

        // Fast S-curve through the middle: precise near vertical, strong near 45 degrees.
        constexpr float kAngleStart = 0.10f;
        constexpr float kAngleFull = 0.72f;
        float angleT = std::clamp((steerRatio - kAngleStart) / (kAngleFull - kAngleStart), 0.0f, 1.0f);
        angleT = angleT * angleT * (3.0f - 2.0f * angleT);
        float duty = 0.16f + 0.80f * angleT;

        const float radial = std::clamp((magnitude - 0.17f) / 0.83f, 0.0f, 1.0f);
        duty *= 0.76f + 0.24f * radial;

        // Deliberate diagonals get an authority floor. This restores a visible curved
        // path without going back to permanently held UP+RIGHT/DOWN+LEFT.
        const float diagonalness = axisSum > 0.0001f ? 1.0f - (std::abs(ax - ay) / axisSum) : 0.0f;
        float diagonalGate = std::clamp((std::min(ax, ay) - 0.22f) / 0.30f, 0.0f, 1.0f);
        diagonalGate = diagonalGate * diagonalGate * (3.0f - 2.0f * diagonalGate);
        if (diagonalness >= 0.62f && diagonalGate > 0.0f) {
            duty = std::max(duty, (0.66f + 0.10f * radial) * diagonalGate);
        }
        duty = std::clamp(duty, 0.12f, 0.96f);

        // A quadrant/reverse transition is immediate and discards stale steering credit.
        if (effectiveTurnSign != modernTurnSign_ || moveSign != modernMoveSign_) {
            modernTurnSign_ = effectiveTurnSign;
            modernMoveSign_ = moveSign;
            modernTurnAccumulator_ = 1.0f;
            modernTurnBurstRemaining_ = 0;
        }

        // Adaptive Arc Scheduler. R5 scattered isolated one-frame turn samples, which
        // many tank-control games barely express. R6 spends the same fractional budget
        // in coherent 1/2/3-frame diagonal bursts so curves feel continuous and natural.
        modernTurnAccumulator_ = std::min(4.0f, modernTurnAccumulator_ + duty);
        if (modernTurnBurstRemaining_ <= 0 && modernTurnAccumulator_ >= 0.72f) {
            modernTurnBurstRemaining_ = duty >= 0.68f ? 3 : (duty >= 0.34f ? 2 : 1);
        }

        if (modernTurnBurstRemaining_ > 0) {
            mask |= modernButtonBit(effectiveTurnSign < 0 ? 6u : 7u);
            modernTurnBurstRemaining_--;
            modernTurnAccumulator_ = std::max(0.0f, modernTurnAccumulator_ - 1.0f);
        }

        modernTankButtons_.store(mask, std::memory_order_release);
]=])
arc_replace_required("${OLD}" "${NEW}" "adaptive moving arc resolver")

file(WRITE "${OMNICORE_ARC_HOST_OUTPUT}" "${SOURCE}")
message(STATUS "OmniCore PS1 Adaptive Arc Steering R6 host generated: ${OMNICORE_ARC_HOST_OUTPUT}")
